title: Anime expressions simplified
hero_image: images/banner.png
description: Create and style a web page for an anime drawing tutorial.
meta_title: Learn CSS | Learn web development | Anime expressions
meta_description: Learn web development for beginners with the Raspberry Pi Foundation. Learn CSS and use styles to apply layouts, colour palettes, and fonts to your web page. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-11"
steps:
  - title: Introduction
  - title: Add a heading to your web page
  - title: Add content to the main section
  - title: Add paragraph text
  - title: Add a facial expression
    completion: engaged
  - title: Style your page
  - title: Edit your style sheet
  - title: Style with classes
  - title: Make your page responsive
  - title: Colours and fonts
    completion: internal
  - title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
