title: Anime expressions
hero_image: images/banner.png
description: Create and style a webpage for an anime drawing tutorial.
meta_title: Learn CSS | Learn web development | Anime expressions
meta_description: Learn web development for beginners with the Raspberry Pi Foundation. Learn CSS and use styles to apply layouts, colour palettes, and fonts to your webpage. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-11"
steps:
  - title: Introduction
  - title: Start your webpage
  - title: Add a facial expression
    completion: engaged
  - title: Style your page
  - title: Style with classes
  - title: Colours and fonts
    completion: internal
  - title: Reflection
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
